# Generated by Django 6.0.4 on 2026-04-11 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("mail", models.EmailField(max_length=254)),
                ("websitePessoal", models.URLField()),
                ("foto", models.ImageField(upload_to="fotos_docentes/")),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("creditos", models.IntegerField()),
                ("avaliacao", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("capa", models.ImageField(upload_to="capa_unidades/")),
                ("docentes", models.ManyToManyField(to="portfolio_app.docente")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.licenciatura",
                    ),
                ),
            ],
        ),
    ]
