# Generated by Django 6.0.4 on 2026-04-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_docente_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("expertise", models.IntegerField()),
                ("logo", models.ImageField(upload_to="logos_tecnologias/")),
                ("websiteOficial", models.URLField()),
                ("review", models.TextField()),
            ],
        ),
    ]
