# Generated by Django 6.0.4 on 2026-04-11 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0003_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("linkItch", models.URLField()),
                ("imagem", models.ImageField(upload_to="imagens_projetos/")),
                ("avaliacao", models.IntegerField()),
                (
                    "UnidadeCurricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.unidadecurricular",
                    ),
                ),
                ("tecnologias", models.ManyToManyField(to="portfolio_app.tecnologia")),
            ],
        ),
    ]
