# Generated by Django 6.0.4 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0004_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("expertise", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(to="portfolio_app.competencia"),
        ),
    ]
