# Generated by Django 6.0.4 on 2026-04-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0005_competencia_projeto_competencias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gamejam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("nomeJogo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("linkItch", models.URLField()),
                ("imagem", models.ImageField(upload_to="imagens_gamejams/")),
                ("classificacao", models.IntegerField()),
                (
                    "competencias",
                    models.ManyToManyField(to="portfolio_app.competencia"),
                ),
                ("tecnologias", models.ManyToManyField(to="portfolio_app.tecnologia")),
            ],
        ),
    ]
