# Generated by Django 6.0.4 on 2026-04-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0006_gamejam"),
    ]

    operations = [
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(to="portfolio_app.tecnologia"),
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("instituicao", models.CharField(max_length=200)),
                ("dataInicio", models.DateField()),
                ("dataFim", models.DateField()),
                (
                    "competencias",
                    models.ManyToManyField(to="portfolio_app.competencia"),
                ),
            ],
        ),
    ]
