# Generated by Django 6.0.4 on 2026-04-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0007_competencia_tecnologias_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricaoDecisao", models.TextField()),
                ("errosEncontrados", models.TextField()),
                ("justificacaoModelacao", models.TextField()),
                ("usoAI", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOfImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_makingof/")),
                ("legenda", models.TextField()),
                (
                    "makingof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="portfolio_app.makingof",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("link_pdf", models.URLField()),
                ("imagem", models.ImageField(upload_to="imagens_tfcs/")),
                ("rating", models.IntegerField()),
                ("autores", models.ManyToManyField(to="portfolio_app.autor")),
                (
                    "competencias",
                    models.ManyToManyField(to="portfolio_app.competencia"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.licenciatura",
                    ),
                ),
                ("orientadores", models.ManyToManyField(to="portfolio_app.docente")),
                ("tecnologias", models.ManyToManyField(to="portfolio_app.tecnologia")),
            ],
        ),
    ]
