# Generated by Django 6.0.4 on 2026-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0008_autor_makingof_makingofimagem_tfc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docente",
            name="websitePessoal",
        ),
        migrations.AddField(
            model_name="docente",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
