# Generated by Django 6.0.4 on 2026-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0009_remove_docente_websitepessoal_docente_resumo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(blank=True, to="portfolio_app.docente"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(blank=True, to="portfolio_app.docente"),
        ),
    ]
