# Generated by Django 6.0.4 on 2026-04-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0011_alter_competencia_tecnologias_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="docente",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="classificacao",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagens_gamejams/"
            ),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="linkItch",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="ano",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="avaliacao",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="linkItch",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="semestre",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.competencia"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(blank=True, to="portfolio_app.docente"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(blank=True, to="portfolio_app.docente"),
        ),
    ]
