# Generated by Django 6.0.4 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0012_alter_competencia_tecnologias_alter_docente_mail_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_docentes/"),
        ),
    ]
