# Generated by Django 6.0.4 on 2026-04-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0013_alter_docente_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="competencia",
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="docente",
            options={"verbose_name": "Docente", "verbose_name_plural": "Docentes"},
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"verbose_name": "Formação", "verbose_name_plural": "Formações"},
        ),
        migrations.AlterModelOptions(
            name="gamejam",
            options={"verbose_name": "GameJam", "verbose_name_plural": "GameJams"},
        ),
        migrations.AlterModelOptions(
            name="licenciatura",
            options={
                "verbose_name": "Licenciatura",
                "verbose_name_plural": "Licenciaturas",
            },
        ),
        migrations.AlterModelOptions(
            name="makingof",
            options={"verbose_name": "MakingOf", "verbose_name_plural": "MakingOfs"},
        ),
        migrations.AlterModelOptions(
            name="makingofimagem",
            options={
                "verbose_name": "MakingOfImagem",
                "verbose_name_plural": "MakingOfImagens",
            },
        ),
        migrations.AlterModelOptions(
            name="projeto",
            options={"verbose_name": "Projeto", "verbose_name_plural": "Projetos"},
        ),
        migrations.AlterModelOptions(
            name="tecnologia",
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"verbose_name": "TFC", "verbose_name_plural": "TFCs"},
        ),
        migrations.AlterModelOptions(
            name="unidadecurricular",
            options={
                "verbose_name": "Unidade Curricular",
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
    ]
