# Generated by Django 6.0.4 on 2026-04-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0014_alter_autor_options_alter_competencia_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamejam",
            options={"verbose_name": "Game Jam", "verbose_name_plural": "Game Jams"},
        ),
    ]
