# Generated by Django 6.0.4 on 2026-04-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0015_alter_gamejam_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="UnidadeCurricular",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio_app.unidadecurricular",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="imagens_projetos/"),
        ),
    ]
