# Generated by Django 6.0.4 on 2026-04-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0016_alter_projeto_unidadecurricular_alter_projeto_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="UnidadeCurricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio_app.unidadecurricular",
            ),
        ),
    ]
