# Generated by Django 6.0.4 on 2026-04-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0017_alter_projeto_unidadecurricular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.ManyToManyField(blank=True, to="portfolio_app.autor"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagens_tfcs/"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
