# Generated by Django 6.0.4 on 2026-04-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0018_alter_tfc_autores_alter_tfc_imagem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="creditos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="instituicao",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="avaliacao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="creditos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
