# Generated by Django 6.0.4 on 2026-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0019_alter_licenciatura_creditos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formacao",
            name="tecnologia",
            field=models.ManyToManyField(blank=True, to="portfolio_app.tecnologia"),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="classificacao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamejam",
            name="nomeJogo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
