# Generated by Django 6.0.4 on 2026-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0020_formacao_tecnologia_alter_gamejam_classificacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formacao",
            name="nivel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="dataFim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="dataInicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="instituicao",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
