# Generated by Django 6.0.4 on 2026-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0021_formacao_nivel_alter_formacao_datafim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
