# Generated by Django 6.0.5 on 2026-05-08 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_alter_artigo_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artigo",
            name="likes",
        ),
        migrations.AddField(
            model_name="artigo",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="likes_artigos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
