# Generated by Django 6.0.5 on 2026-05-08 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0003_remove_artigo_likes_artigo_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes_artigos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
